// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApprovePlanRequest struct {
	ID string `path:"id"`
}

type CreateProjectRequest struct {
	Path string `json:"path"`
}

type CreateSessionRequest struct {
	ProjectPath string `json:"project_path"`
	Model       string `json:"model,optional"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

type GetProjectRequest struct {
	Name string `path:"name"`
}

type GetSessionRequest struct {
	ID string `path:"id"`
}

type ProjectListResponse struct {
	Projects []ProjectResponse `json:"projects"`
}

type ProjectResponse struct {
	Path     string   `json:"path"`
	Sessions []string `json:"sessions"`
}

type SessionEvent struct {
	Type      string                 `json:"type"`
	SessionID string                 `json:"session_id"`
	Timestamp string                 `json:"timestamp"`
	Data      map[string]interface{} `json:"data"`
}

type SessionListRequest struct {
	ProjectPath string `form:"project_path,optional"`
}

type SessionListResponse struct {
	Sessions []SessionResponse `json:"sessions"`
}

type SessionResponse struct {
	ID          string `json:"id"`
	ProjectPath string `json:"project_path"`
	Model       string `json:"model"`
	State       string `json:"state"`
	CreatedAt   string `json:"created_at"`
	BlockedOn   string `json:"blocked_on,optional"`
	BlockedTool string `json:"blocked_tool,optional"`
}

type StreamSessionEventsRequest struct {
	ID string `path:"id"`
}

type SubmitInputRequest struct {
	ID    string `path:"id"`
	Input string `json:"input"`
	Mode  string `json:"mode,optional"`
}

type UnblockRequest struct {
	ID         string `path:"id"`
	Response   string `json:"response"`
	Approved   bool   `json:"approved"`
	AddAllowed string `json:"add_allowed,optional"`
}
