// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApprovePlanRequest struct {
	ID string `path:"id"`
}

type ChatMessage struct {
	Role             string     `json:"role"`
	Content          string     `json:"content,optional"`
	ReasoningContent string     `json:"reasoning_content,optional"`
	ToolCalls        []ToolCall `json:"tool_calls,optional"`
	ToolCallID       string     `json:"tool_call_id,optional"`
}

type CreateProjectRequest struct {
	Path string `json:"path"`
}

type CreateSessionRequest struct {
	ProjectPath string `json:"project_path"`
	Model       string `json:"model,optional"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

type FunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

type GetProjectRequest struct {
	Name string `path:"name"`
}

type GetSessionRequest struct {
	ID string `path:"id"`
}

type ProjectListResponse struct {
	Projects []ProjectResponse `json:"projects"`
}

type ProjectResponse struct {
	Path         string   `json:"path"`
	Sessions     []string `json:"sessions"`
	LastModified string   `json:"last_modified"`
}

type RemoveSessionFromProjectRequest struct {
	Name      string `path:"name"`
	SessionID string `path:"session_id"`
}

type SessionEvent struct {
	Type      string                 `json:"type"`
	SessionID string                 `json:"session_id"`
	Timestamp string                 `json:"timestamp"`
	Data      map[string]interface{} `json:"data"`
}

type SessionListRequest struct {
	ProjectPath string `form:"project_path,optional"`
}

type SessionListResponse struct {
	Sessions []SessionResponse `json:"sessions"`
}

type SessionResponse struct {
	ID          string                 `json:"id"`
	ProjectPath string                 `json:"project_path"`
	Model       string                 `json:"model"`
	State       string                 `json:"state"`
	Mode        string                 `json:"mode"`
	CreatedAt   string                 `json:"created_at"`
	Input       string                 `json:"input"`
	Messages    []ChatMessage          `json:"messages"`
	BlockedOn   string                 `json:"blocked_on,optional"`
	BlockedTool string                 `json:"blocked_tool,optional"`
	BlockedArgs map[string]interface{} `json:"blocked_args,optional"`
}

type StreamSessionEventsRequest struct {
	ID string `path:"id"`
}

type SubmitInputRequest struct {
	ID    string `path:"id"`
	Input string `json:"input"`
	Mode  string `json:"mode,optional"`
}

type ToolCall struct {
	ID       string       `json:"id"`
	Type     string       `json:"type"`
	Function FunctionCall `json:"function"`
}

type UnblockRequest struct {
	ID         string `path:"id"`
	Approved   bool   `json:"approved"`
	AddAllowed string `json:"add_allowed,optional"`
}
