// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	"agent-base/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/config/llm",
				Handler: GetLLMConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/config/llm",
				Handler: UpdateLLMConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects",
				Handler: ListProjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/projects",
				Handler: CreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects/:name",
				Handler: GetProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/projects/:name/sessions/:session_id",
				Handler: RemoveSessionFromProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions",
				Handler: CreateSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sessions",
				Handler: ListSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sessions/:id",
				Handler: GetSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions/:id/approve",
				Handler: ApprovePlanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions/:id/input",
				Handler: SubmitInputHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions/:id/unblock",
				Handler: UnblockSessionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sessions/:id/events",
				Handler: StreamSessionEventsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(3600000*time.Millisecond),
		rest.WithSSE(),
	)
}
